### ISSUE TITLE
Spurious build success when compiling directories with wonky files

### ISSUE THREAD

**Issue by theindigamer** [ollef/sixten#131]
This isn't a minimal repro (I'm trying to make one, no success yet) but this does reproduce the problem I was talking about.

    $ cd tests/success/00-basics
    $ echo "data X = (" > Empty.vix && sixten check .
    Type checking returned successfully

This is a problem on old `master` (at `4aa97c94`), as well as after my PR.

**Comment by ollef** [comment]
Good find!

I'm not 100% sure, but this might actually be due to https://github.com/ollef/sixten/issues/130, because it's happening in a directory where multiple files (implicitly) define the module `Main`. You get the syntax error again if you instead put this in the file:

```haskell
module Empty exposing (..)

data X = (
```
