### ISSUE TITLE
Dot patterns/forced patterns

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#136]
There needs to be a way to mark a function argument as being equal to something without pattern matching on it, because of equalities revealed by pattern matching on something else. For example,

```haskell
f : (x : Int) -> Equals x 610 -> Unit
f 610 Refl = MkUnit
```

does not have to pattern match on the `Int` because it's forced by the equality.

The implementation seems straightforward, following http://www2.tcs.ifi.lmu.de/~abel/lhs-checking-submitted.pdf. We have to add syntax, and add a check that the dotted patterns are equal to the terms that are being matched.

Agda uses `.` as the syntax for this, i.e. `.610`. This syntax is a bit problematic in Sixten because Sixten uses dots for lambdas, so `\x. e ...` is ambiguous because it could parse as a two-argument lambda where the second is a dot pattern, `.e`, or a one argument lambda with body `e`.

I see the following options:

1. Come up with a different syntax for forced patterns. Maybe `^e` or `*e`? Suggestions?
1. Change the lambda syntax to `\x -> e`, in line with Haskell and Agda.
1. Be whitespace sensitive. Enforce that the pattern dot has to have to whitespace after it, so `\x. e` is a single-argument lambda, and `\x .e1. e2` is a two-argument lambda with a dotted pattern.

**Comment by mbakhterev** [comment]
The 3rd variant is very confusing. Avoid it, please.

**Comment by ollef** [comment]
Yeah, I agree. I'm leaning towards 2 at the moment.

**Comment by ollef** [comment]
If we change the lambda syntax we should also change the `forall x. t` syntax (for introducing implicit parameters) because it also accepts a list of patterns before the dot.

This would take some time to get used to. I really prefer `forall x. t` over `forall x -> t`.

**Comment by brendanzab** [comment]
Another option might be `forall x, t` and `\x, t` - I think this is what Lean does.

**Comment by ollef** [comment]
Ended up going for `~pat`, as it seemed nicer than the alternatives :woman_shrugging:
