### ISSUE TITLE
Optimise closure representation

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#37]
Perhaps we can e.g. store the arity of the closure as a bitfield where the highest set bit determines the arity and the other set bits determine the arguments of size 8 (assuming that word-sized data will be the most common to use).

**Comment by Josef-Vonasek** [comment]
What is the current representation?

**Comment by ollef** [comment]
We're currently using something like option 2 in the rather cryptic document on closure conversion: https://github.com/ollef/sixten/blob/master/docs/ClosureConversion.md

Basically:

When applying a known function to too few arguments we capture them like so:
* Raw function pointer (machine word)
* Remaining arity (int)
* `arg1` (whatever size `arg1` has)
* ...
* `argn` (whatever size `argn` has)

This is pretty much as good as it gets.

BUT, if you apply an unknown function to some arguments and it's still a partial application, it also stores the _size_ of all the arguments. That's this line in the document:

```
    | m < n -> Ref (CL pap(n-m),m (n - m) xthis x1size .. xmsize x1 .. xm)
```

The reason for this is that the `apply` family of functions need to know the sizes of its arguments to be able to build closures of the correct size, and the `pap` function in the above closure uses `apply`

Depnding on the code this might be somewhat of a corner case and not that important, but it still feels a little wasteful, especially if you expect that most arguments are of word size.

**Comment by Josef-Vonasek** [comment]
What not store them like this:

* arity
* arg1 size
* arg1
* arg2 size
* arg2
* ...
* if partial: pointer to closure

**Comment by ollef** [comment]
That's the same as the current one, just a different order. Why is that order better?

**Comment by Josef-Vonasek** [comment]
Oh, my bad. Your version is better. 

1. 5. 2018 2:37 PM, 2:37 PM, Olle Fredriksson <notifications@github.com> napsal/a:

**Comment by ollef** [comment]
No worries :)

**Comment by ollef** [comment]
Probably not important enough to have an issue at this stage.
