### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#40]
Should run test.sh.

**Comment by vic** [comment]
I'd like to work on this one.

**Comment by ollef** [comment]
Awesome! Yeah, that'd be ideal. Let us know if you need any help!

**Comment by vic** [comment]
@ollef Thanks for merging <3

I'll try to help more and send some PR for other low hanging fruit :)

**Comment by ollef** [comment]
Hurray, that's great to hear!

Would you be interested in having a chat set up somewhere for Sixten devs?

**Comment by vic** [comment]
Sure, are you ok with using something like gitter.im, or prefer slack, I'm more inclined to the first as it requires almost nothing to setup, you just need to login on gitter (as sixten maintainer) and register the room. If you prefer slack I could register one.

**Comment by ollef** [comment]
I haven't yet used gitter, but it sounds good so I just set it up for the repository. Good suggestion!
