### ISSUE TITLE
Add comparison to intensional polymorphism in readme

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#41]
Intensional polymorphism or intensional type analysis is an idea related to how our representation polymorphism is handled that should probably be mentioned in the readme.

**Comment by ollef** [comment]
See also the paper on TIL: https://www.cs.cmu.edu/~rwh/papers/til/pldi96.pdf

**Comment by glaebhoerl** [comment]
(BTW it's spelled inten*s*ional with an S :)

**Comment by ollef** [comment]
Oops, thanks!

**Comment by ollef** [comment]
@glaebhoerl (or others): Do you think the comparison in the above commit is fair?

**Comment by glaebhoerl** [comment]
I'm not an expert. According to @AndrasKovacs, Sixten's representation and the one you're contrasting it to in the comment *both* qualify as being intensional polymorphism. Maybe he can explain it better :)

**Comment by ollef** [comment]
Yeah, that'd be interesting to hear! Hopefully @AndrasKovacs will see this.

Sixten would qualify if we take "intensional polymorphism" to mean the use of type representations at runtime, which might be what Andras is thinking of. And I also think this is a reasonable definition of the term. However, in [1] it seems to me that they're thinking of a more specific thing when they use it:

```
By "intensional polymorphism", we mean that constructors and terms can be constructed via structural recursion on types.
```

Structural recursion on types is not supported in Sixten, neither in the surface language or any intermediate languages.

[1] Harper, Robert, and Greg Morrisett. "Compiling polymorphism using intensional type analysis." Proceedings of the 22nd ACM SIGPLAN-SIGACT symposium on Principles of programming languages. ACM, 1995.

**Comment by ollef** [comment]
Merging what I have now. Feel free to continue the discussion, suggest edits, etc.
