### ISSUE TITLE
Typo (?) in license file

### ISSUE THREAD

**Issue by theindigamer** [ollef/sixten#42]
Hi! Just saw your project on r/haskell; I have to admit it looks pretty cool as an enthusiast :smile:.

Looking at the license, I think you're going for BSD 3-clause license but the [third line](https://github.com/ollef/sixten/blob/da44703796b59aa71430aabe3f34163ec666fed9/LICENSE#L3) doesn't seem quite right ... is that a typo?

**Comment by ollef** [comment]
Hey! Thanks!

I believe this is standard. See https://en.wikipedia.org/wiki/BSD_licenses and https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved.
