### ISSUE TITLE
Add `check` command

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#64]
Add a `sixten check` command to the command-line interface that runs the typechecker but doesn't go further, which will be faster than using `compile` when you just want to see if something typechecks.

**Comment by brandonhamilton** [comment]
I'm interested in building this and have a question on what the preferable implementation of this feature should be:

- Should it return after running the only the [frontend](https://github.com/ollef/sixten/blob/8025d05054f6e4948cdad5501f131ab7314b3879/src/Processor/File.hs#L56) on each module, which would require additional options passed through and changes to be made to the [Processor.Files](https://github.com/ollef/sixten/blob/master/src/Processor/Files.hs) module.

- Or, run the full [frontend and backend](https://github.com/ollef/sixten/blob/master/src/Processor/File.hs#L51) processing and then return before writing the modules out to disk and running llvm. This would need only a minor change to the processor, but would be doing more work.

I would assume the first option, but just wanted to check before submitting the implementation.

**Comment by ollef** [comment]
Yeah, the first option is what I had in mind.

I'll have a look at your PR now.
