### ISSUE TITLE
Use llvm-config to find the LLVM binary directory

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#65]
llvm-config is able to provide the directory that the system places the LLVM binaries in.

We should also make the `llvm-config` binary configurable on the command-line, which would provide a way to use the compiler on systems like Ubuntu where the LLVM-binaries on the PATH have their versions appended (e.g. `opt-5.0`, see discussion in #9). They can then use e.g. `sixten compile --llvm-config=llvm-config-5.0`. We might also want to consider just trying e.g. `llvm-config-5.0` if `llvm-config` doesn't exist.

**Comment by theindigamer** [comment]
For automatically trying different options, should the logic look like

1. List all binaries named `llvm-config-*` under `PATH`. Return an error if this list is empty.
2. Use the latest version for which all binaries are available (check inside folder `llvm-config-X.Y --bindir`). Return an error if there is no version with all binaries.

On that note, we should add a small setup/installation thing to the Readme or somewhere else. Is Windows a target?

**Comment by ollef** [comment]
I think we should stick to versions that we know that we support, so either option 1 with a whitelist or just a list of names to try. Users can then use the `--llvm-config` flag to override the default behavior. What do you think?

Those are good ideas. I'll make issues about them, cheers!

**Comment by theindigamer** [comment]
That works too. What LLVM versions do you want to support before 5.0? Just 4.0 or earlier as well? This [page](http://blog.llvm.org/2016/12/llvms-new-versioning-scheme.html) says that a new major version will appear every 6 months. LLVM 5 came out in Sept 2017 and LLVM 4 released in Mar 2017. As an example, Ubuntu's default repositories aren't updated as frequently as Arch and so the virtual package `llvm` currently refers to `llvm-4.0`.

**Comment by ollef** [comment]
It sounds like a good idea to try to include LLVM 4 too to get more convenient Ubuntu support, provided it works. :)
