### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ollef** [ollef/sixten#69]
It'd be nice if we could run Sixten on Windows. We should:

- [ ] Check if Sixten works on Windows.
- [ ] If it doesn't, try to fix it, or put any errors here and see if anyone else knows how to fix it.
- [ ] Write installation instructions for the README (if they differ from any existing installation instructions).
- [ ] Look into the possibility of running automated tests on Windows.

**Comment by ollef** [comment]
I don't actually know if this is beginner-friendly, but it might be if you're used to building Haskell stuff on Windows. :)

**Comment by brandonhamilton** [comment]
I can confirm that sixten compiles with stack on Windows 10.

The frontend runs successfully (i.e. `sixten check`).

Minor modifications are needed for the llvm tools (`llvm-config` doesn't exist in Windows, so need to use `clang-cl.exe` instead).

The outstanding challenge I have is to compile the Boehm–Demers–Weiser GC library on windows to enable assembly.

**Comment by ollef** [comment]
Nice, then we're in better shape than I thought!

Are the changes you made something that could be integrated into Sixten in some form?

**Comment by ollef** [comment]
@sighingnow has added Windows support now. :D
